const app = require('express')()
const bodyparser = require('body-parser')
const cors = require('cors')
const handleHttprequest = require('./controller/HandleHttprequest')
app.listen(3000, ()=>{
    console.log(`listen at 3000`)
})
app.use(cors())
app.use(bodyparser.json())
app.use('/', handleHttprequest)
